backend:
  name: git-gateway
  branch: master

media_folder: static/media/uploads
public_folder: /media/uploads

collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'src/pages'
    filter: {field: 'templateKey', value: 'page'}
    extension: 'md'
    slug: '{{slug}}'      
    create: true
    editor:
      preview: false    
    fields:
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'page'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'UID', name: 'uid', widget: 'string', pattern: ['^[a-zA-Z0-9_-]*$', 'Cannot have special characters']}
      - {label: 'Main', name: 'mainBody', widget: 'markdown'}
      - {label: 'Allow HTML elements', name: 'allowHtml', widget: 'boolean', default: false}
      - label: 'Side items'
        name: 'sideItems'
        widget: 'list'
        required: false
        fields: [
          {label: 'Content', name: sideItemBody, widget: 'markdown', required: false},
          {label: 'Allow HTML elements', name: 'allowHtml', widget: 'boolean', default: false}
          {label: 'Image (replaces content)', name: 'sideItemImage', widget: image},
          {label: 'Image alt text', name: 'sideItemImageAlt', widget: string},
          {label: 'Background color', name: sideItemBackgroundColor, widget: 'select', default: '#28ffff', options: [
                {label: 'Light blue', value: '#28ffff'},
                {label: 'Pink', value: '#fa6efe'},
                {label: 'Orange', value: '#efb741'},
                {label: 'Black', value: '#000'},
                {label: 'Green', value: '#28ff00'},
                {label: 'Dark blue', value: '#2800ff'},
                {label: 'Purple', value: '#b017d3'},            
                {label: 'Grey', value: '#abc1a5'},
            ]}
        ]
  - name: 'index-page'
    label: 'Index'
    folder: 'src/pages'
    extension: 'md'
    filter: {field: 'templateKey', value: 'index-page'}
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Main', name: 'body', widget: 'markdown', required: false}
      - {label: 'Allow HTML elements', name: 'allowHtml', widget: 'boolean', default: false}    
      - {label: 'Sections', name: 'sections', widget: 'list', fields: [
          {label: 'Header', name: 'sectionHeader', widget: string},
          {label: 'Featured Image', name: 'sectionFeaturedImage', widget: image},
          {label: 'Link', name: 'sectionLink', widget: 'relation', collection: 'pages', searchFields: ['uid', 'title'], valueField: 'uid'},
          {label: 'Content', name: 'sectionBody', widget: 'markdown', required: false},
          {label: 'Allow HTML elements', name: 'allowHtml', widget: 'boolean', default: false}
        ]}
      - {label: 'Footer image', name: 'footerImage', widget: image},
      - {label: 'Footer image alt text', name: 'footerImageAlt', widget: string}, 
  - name: 'settings'
    label: 'Settings'
    editor:
      preview: false    
    files:
      - label: 'Footer'
        name: 'footer'
        file: 'src/settings/footer.md'
        fields:
          - label: 'Address field'
            name: 'body'
            widget: 'markdown'
          - label: 'Social field'
            name: 'social'
            widget: 'markdown'
      - label: 'Navigation'
        name: 'navigation'
        file: 'src/settings/navigation.md'
        fields:
          - label: 'Nav Menu items'
            name: 'navMenu'
            widget: 'list'
            fields:
              - label: 'Link'
                name: 'navMenuItem'
                widget: 'relation'
                collection: 'pages'
                searchFields: ['uid', 'title']
                valueField: 'uid'