backend:
  name: git-gateway
  branch: master
  repo: johanbissemattsson/knashemma
  site_domain: location.hostname
  
media_folder: static/media/uploads
public_folder: /media/uploads

collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'src/pages'
    filter: {field: 'templateKey', value: 'page'}
    extension: 'md'
    slug: '{{slug}}'      
    create: true
    editor:
      preview: false    
    fields:
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'page'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'UID', name: 'uid', widget: 'string', pattern: ['^[a-zA-Z0-9_-]*$', 'Cannot have special characters']}
      - {label: 'Meta information (for SEO)', name: 'metaInformation', widget: 'object', fields: [
          {label: 'Meta page description', name: 'metaDescripton', widget: 'string'},
          {label: 'Meta page keywords', name: 'metaKeywords', widget: 'string'}
        ]
      }
      - {label: 'Header images', name: 'imageSlider', widget: 'list', required: false, fields: [
          {label: 'Image', name: 'imageSliderImage', widget: 'image', required: false},
          {label: 'Image alt text', name: 'imageSliderImageAlt', widget: 'string', required: false},
          {label: 'Link', name: 'imageSliderImageLink', widget: 'relation', collection: 'pages', searchFields: ['uid', 'title'], valueField: 'uid', required: false},          
        ]}      
      - {label: 'Main', name: 'body', widget: 'markdown'}
      - label: 'Side items'
        name: 'sideItems'
        widget: 'list'
        required: false
        fields: [
          {label: 'Content', name: sideItemBody, widget: 'markdown', required: false},
          {label: 'Image (replaces content)', name: 'sideItemImage', widget: 'image', required: false},
          {label: 'Image alt text', name: 'sideItemImageAlt', widget: 'string', required: false},
          {label: 'Background color', name: sideItemBackgroundColor, widget: 'select', default: '#28ffff', options: [
                {label: 'Light blue', value: '#28ffff'},
                {label: 'Pink', value: '#fa6efe'},
                {label: 'Orange', value: '#efb741'},
                {label: 'Black', value: '#000'},
                {label: 'Green', value: '#28ff00'},
                {label: 'Dark blue', value: '#2800ff'},
                {label: 'Purple', value: '#b017d3'},            
                {label: 'Grey', value: '#abc1a5'},
            ]}
        ]
  - name: 'index-page'
    label: 'Index'
    folder: 'src/pages'
    extension: 'md'
    filter: {field: 'templateKey', value: 'index-page'}
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page'}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Meta information (for SEO)', name: 'metaInformation', widget: 'object', fields: [
          {label: 'Meta page description', name: 'metaDescripton', widget: 'string'},
          {label: 'Meta page keywords', name: 'metaKeywords', widget: 'string'}
        ]
      - {label: 'Header images', name: 'imageSlider', widget: 'list', fields: [
          {label: 'Image', name: 'imageSliderImage', widget: 'image'},
          {label: 'Image alt text', name: 'imageSliderImageAlt', widget: 'string'},
          {label: 'Link', name: 'imageSliderImageLink', widget: 'relation', collection: 'pages', searchFields: ['uid', 'title'], valueField: 'uid', required: false},          
        ]}
      - {label: 'Main', name: 'body', widget: 'hidden', required: false}
      - {label: 'Sections', name: 'sections', widget: 'list', fields: [
          {label: 'Header', name: 'sectionHeader', widget: string},
          {label: 'Featured Image', name: 'sectionFeaturedImage', widget: image},
          {label: 'Link', name: 'sectionLink', widget: 'relation', collection: 'pages', searchFields: ['uid', 'title'], valueField: 'uid', required: false},
          {label: 'Content', name: 'sectionBody', widget: 'markdown', required: false},
        ]}
      - {label: 'Footer image', name: 'footerImage', widget: image, required: false}
      - {label: 'Footer image alt text', name: 'footerImageAlt', widget: string, required: false} 
  - name: 'settings'
    label: 'Settings'
    editor:
      preview: false    
    files:
      - label: 'Footer'
        name: 'footer'
        file: 'src/settings/footer.md'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'settings-footer'}
          - label: 'Address field'
            name: 'body'
            widget: 'markdown'
      - label: 'Navigation'
        name: 'navigation'
        file: 'src/settings/navigation.md'
        fields:
          - {label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'settings-navigation'}
          - label: 'Nav Menu items'
            name: 'navMenu'
            widget: 'list'
            fields:
              - label: 'Link'
                name: 'link'
                widget: 'relation'
                collection: 'pages'
                searchFields: ['uid', 'title']
                valueField: 'uid'
              - label: 'Link Title'
                name: 'title'
                widget: 'string'       
              