backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/media/uploads
public_folder: /media/uploads

collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'src/pages'
    extension: 'md'
    filter: {field: "templateKey", value: 'page'}
    slug: '{{slug}}'        
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: 'page'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main", name: "body", widget: "markdown"}
      - {label: "Side", name: "side", widget: "markdown"}
  - name: 'index-page'
    label: 'Index'
    folder: 'src/pages'
    extension: 'md'
    filter: {field: "templateKey", value: 'index-page'}
    create: true
    delete: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: 'index-page'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main", name: "body", widget: "markdown"}
      - {label: 'Sections', name: 'sections', widget: 'list', fields: [
          {label: 'Section', name: 'section', widget: 'object', fields: [
            {label: 'Header', name: sectionHeader, widget: string},
            {label: 'Featured Image', name: sectionFeaturedImage, widget: image},
            {label: 'Link', name: sectionLink, widget: 'relation', collection: 'pages', searchFields: ['name'], valueField: 'name'},
            {label: 'Content', name: sectionBody, widget: 'markdown'}
          ]}
        ]}   