backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/media/uploads
public_folder: /media/uploads

collections:
  - name: 'pages'
    label: 'Pages'
    folder: 'src/pages'
    extension: 'md'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Main", name: "main", widget: "markdown"}
      - {label: "Side", name: "side", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: 'index-page'
    label: 'Index page'
    files:
      - file: "src/pages/index-page/index.md"
        label: "Knas hemma"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Section 1", name: "section1", widget: object, fields:[
              {label: Heading, name: titleSection1, widget: string},
              {label: Description, name: descriptionSection1, widget: text},
          ]}
          - {label: "Section 2", name: "section2", widget: object, fields:[
              {label: Heading, name: titleSection2, widget: string},
              {label: Description, name: descriptionSection2, widget: text}
          ]}
          - {label: "Section 3", name: "section3", widget: object, fields:[
              {label: Heading, name: titleSection2, widget: string},
              {label: Description, name: descriptionSection2, widget: text}
          ]}
          - {label: "Section 4", name: "section4", widget: object, fields:[
              {label: Heading, name: titleSection2, widget: string},
              {label: Description, name: descriptionSection2, widget: text}
          ]}               